"""add relationship between categories and transactions

Revision ID: 1da1c12d2a35
Revises: 5e51c79a9961
Create Date: 2025-11-22 19:01:27.695228

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1da1c12d2a35'
down_revision: Union[str, Sequence[str], None] = '5e51c79a9961'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
