"""remove enum

Revision ID: b21c6392cad1
Revises: c66e9c2b4429
Create Date: 2025-11-22 20:32:51.966959

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b21c6392cad1'
down_revision: Union[str, Sequence[str], None] = 'c66e9c2b4429'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('transactions', 'type',
               existing_type=postgresql.ENUM('income', 'expense', name='transaction_type'),
               type_=sa.String(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('transactions', 'type',
               existing_type=sa.String(),
               type_=postgresql.ENUM('income', 'expense', name='transaction_type'),
               existing_nullable=False)
    # ### end Alembic commands ###
